function f(row,col) {
  x = 20151125;
  n = row+col; # number of diagonal, each containing increasing number of elements by 1.
  n = col + n*(n-1)/2 -2;  # sum of , -2 because col=row=1 gives 2 and should map to 0.
  # After that, each code is generated by taking the previous one, multiplying it by 252533, and then keeping the remainder from dividing that value by 33554393.
  print n;
  while (n-->0) { x=x*252533l; x=int(x%33554393); if (++i<10) print x;}
  return x;
}
{ print "row="$1" col="$2" output="f($1,$2); }
