#include <stdint.h>
#include <iostream>

int64_t f(int row,int col) {
  int64_t x = 20151125;
  int n = row+col-1;     // number of diagonal, each containing increasing number of elements by 1.
  n = col-1 + n*(n-1)/2;  // sum of , -2 because col=row=1 gives 2 and should map to 0.
  // After that, each code is generated by taking the previous one, multiplying it by 252533, and then keeping the remainder from dividing that value by 33554393.
  for (int i=0; i<n; ++i) { x*=252533l; x%=33554393; if (i<10) std::cout << x << std::endl;}
  return x;
}
int main() {
  int row=3010, col=3019;
  std::cout << f(row, col) << std::endl;
  return 0;
}
